# Ansible Tower Dockerfie
FROM centos:7

RUN cat /etc/redhat-release
#cat /etc/redhat-release
#CentOS Linux release 7.9.2009 (Core)

WORKDIR /opt

ENV ANSIBLE_TOWER_VER 3.8.5-1
ENV PG_DATA /var/lib/postgresql/9.6/main
ENV AWX_PROJECTS /var/lib/awx/projects
ENV LC_ALL "en_US.UTF-8"
ENV LANGUAGE "en_EN:en"
ENV LANG "en_US.UTF-8"
ENV DEBIAN_FRONTEND "noninteractive"
#ADD http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-${ANSIBLE_TOWER_VER}.tar.gz ansible-tower-setup-${ANSIBLE_TOWER_VER}.tar.gz
COPY docker-entrypoint.sh /docker-entrypoint.sh
COPY inventory inventory

RUN yum -qq update \
	&& yum -yqq upgrade \
	&& yum -yqq install \
			locales \
			gnupg2 \
			gnupg \
			libpython2.7 \
			python \
			python-pip \
			python-dev \
			ca-certificates \
			debconf \
			apt-transport-https \
			sudo


RUN yum install -y epel-release \
    &&  yum -y install ansible vim curl deltarpm wget \
    &&  yum -y install yum-utils \
    &&  yum -y install python \
    &&  yum -y install python-pip \
    &&  yum -y install python-dev \
    &&  yum -y install python-devel \
    &&  yum -y install vim curl postgresql


RUN mkdir -p /var/log/tower \
	&& tar xzvf ansible-tower-setup-${ANSIBLE_TOWER_VER}.tar.gz \
 	&& rm -f ansible-tower-setup-${ANSIBLE_TOWER_VER}.tar.gz \
	&& mv inventory ansible-tower-setup-${ANSIBLE_TOWER_VER}/inventory






